/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author kavya
 */
public class MainSupplier extends javax.swing.JFrame {

    private ResourceBundle english;
    private ResourceBundle french;
    Controller controller = Controller.getInstance();
    /**
     * Creates new form MainLibrarian
     */
    
    Connection con;
    PreparedStatement pst;/**
     * Creates new form MainSupplier
     */
    public MainSupplier() {
        initComponents();
        english = ResourceBundle.getBundle("Language_English");
        french = ResourceBundle.getBundle("Language_French", Locale.FRANCE);

        jButtonSaveDetail.setEnabled(false);
        jButtonSearchBook.setEnabled(false);
        jTextFieldSNSupp.setEnabled(false);
        jTextFieldTitleSupp.setEnabled(false);
        jTextFieldAuthorSupp.setEnabled(false);
        jTextFieldPublisherSupp.setEnabled(false);
        jTextFieldGenreSupp.setEnabled(false);
        jTextFieldQuantitySupp.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaBooks = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelMainSupplier = new javax.swing.JLabel();
        jRadioButtonSearchTitle = new javax.swing.JRadioButton();
        jRadioButtonSellBoook = new javax.swing.JRadioButton();
        jTextFieldQuantitySupp = new javax.swing.JTextField();
        jLabelTitleSupplier = new javax.swing.JLabel();
        jLabelAuthorSupplier = new javax.swing.JLabel();
        jLabelPublisherSupplier = new javax.swing.JLabel();
        jLabelGenreSupplier = new javax.swing.JLabel();
        jTextFieldSNSupp = new javax.swing.JTextField();
        jTextFieldTitleSupp = new javax.swing.JTextField();
        jTextFieldAuthorSupp = new javax.swing.JTextField();
        jLabelBooksSupplier = new javax.swing.JLabel();
        jLabelSNSupplier = new javax.swing.JLabel();
        jTextFieldPublisherSupp = new javax.swing.JTextField();
        jButtonSaveDetail = new javax.swing.JButton();
        jButtonSearchBook = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaBooksSupp = new javax.swing.JTextArea();
        jLabelListBooksSupp = new javax.swing.JLabel();
        jRadioButtonSearchSN = new javax.swing.JRadioButton();
        jTextFieldGenreSupp = new javax.swing.JTextField();
        jLabelQuantitySupplier = new javax.swing.JLabel();
        jRadioButtonEnglish = new javax.swing.JRadioButton();
        jRadioButtonFrench = new javax.swing.JRadioButton();

        jTextAreaBooks.setColumns(20);
        jTextAreaBooks.setRows(5);
        jScrollPane4.setViewportView(jTextAreaBooks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMainSupplier.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 24)); // NOI18N
        jLabelMainSupplier.setText("Supplier");

        buttonGroup1.add(jRadioButtonSearchTitle);
        jRadioButtonSearchTitle.setToolTipText("");
        jRadioButtonSearchTitle.setLabel("Search Book by Title");
        jRadioButtonSearchTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSearchTitleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSellBoook);
        jRadioButtonSellBoook.setText("Sell Book");
        jRadioButtonSellBoook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSellBoookActionPerformed(evt);
            }
        });

        jTextFieldQuantitySupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantitySuppActionPerformed(evt);
            }
        });

        jLabelTitleSupplier.setText("Title");

        jLabelAuthorSupplier.setText("Author");

        jLabelPublisherSupplier.setText("Publisher");

        jLabelGenreSupplier.setText("Genre");

        jLabelBooksSupplier.setText("Books");

        jLabelSNSupplier.setText("SN");

        jButtonSaveDetail.setText("Save");
        jButtonSaveDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDetailActionPerformed(evt);
            }
        });

        jButtonSearchBook.setText("Search");
        jButtonSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchBookActionPerformed(evt);
            }
        });

        jTextAreaBooksSupp.setColumns(20);
        jTextAreaBooksSupp.setRows(5);
        jScrollPane5.setViewportView(jTextAreaBooksSupp);

        jLabelListBooksSupp.setText("List of Books");

        buttonGroup1.add(jRadioButtonSearchSN);
        jRadioButtonSearchSN.setText("Search book by SN");
        jRadioButtonSearchSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSearchSNActionPerformed(evt);
            }
        });

        jTextFieldGenreSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenreSuppActionPerformed(evt);
            }
        });

        jLabelQuantitySupplier.setText("Quantity");

        buttonGroup2.add(jRadioButtonEnglish);
        jRadioButtonEnglish.setText("English");
        jRadioButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEnglishActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonFrench);
        jRadioButtonFrench.setText("French");
        jRadioButtonFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFrenchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSearchSN)
                                    .addComponent(jRadioButtonSellBoook, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonSaveDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSearchBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelBooksSupplier)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSNSupplier)
                                            .addComponent(jTextFieldSNSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTitleSupplier))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelGenreSupplier)
                                            .addComponent(jLabelPublisherSupplier)
                                            .addComponent(jTextFieldPublisherSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTitleSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAuthorSupplier))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldGenreSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelQuantitySupplier)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldAuthorSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextFieldQuantitySupp))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelMainSupplier)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonFrench)
                            .addComponent(jRadioButtonEnglish)))
                    .addComponent(jLabelListBooksSupp)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jRadioButtonEnglish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFrench)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelMainSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonSearchTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonSearchSN)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonSellBoook))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelBooksSupplier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelSNSupplier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSNSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPublisherSupplier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPublisherSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTitleSupplier)
                                    .addComponent(jLabelGenreSupplier))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTitleSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGenreSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAuthorSupplier)
                                    .addComponent(jLabelQuantitySupplier))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldAuthorSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldQuantitySupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSaveDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabelListBooksSupp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jLabelGenreSupplier.getAccessibleContext().setAccessibleName("Quantity to Sell");
        jLabelGenreSupplier.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQuantitySuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantitySuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantitySuppActionPerformed

    private void jButtonSaveDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDetailActionPerformed

//        Controller.getInstance();
        if(jRadioButtonSellBoook.isSelected()){
            int SN =Integer.parseInt(jTextFieldSNSupp.getText());
            String title=(jTextFieldTitleSupp.getText());
            String author = jTextFieldAuthorSupp.getText();
            String  pub=jTextFieldPublisherSupp.getText();
            String genre= jTextFieldGenreSupp.getText();
            int quantity= Integer.parseInt(jTextFieldQuantitySupp.getText());
            jTextAreaBooksSupp.setText(controller.addNewBooktoSell(SN, title, author, pub, genre, quantity));
            jTextFieldSNSupp.setText("");
            jTextFieldTitleSupp.setText("");
            jTextFieldAuthorSupp.setText("");
            jTextFieldPublisherSupp.setText("");
            jTextFieldGenreSupp.setText("");
            jTextFieldQuantitySupp.setText("");
        }
        
        
    }//GEN-LAST:event_jButtonSaveDetailActionPerformed

    private void jButtonSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchBookActionPerformed
//        Controller.getInstance();
        if(jRadioButtonSearchSN.isSelected()){
            jTextAreaBooksSupp.setText("");
            jTextAreaBooksSupp.setText(controller.searchBookSellSN(Integer.parseInt(jTextFieldSNSupp.getText())));
            jTextFieldSNSupp.setText("");
        }
        
        else if(jRadioButtonSearchTitle.isSelected()){
            jTextAreaBooksSupp.setText("");
            jTextAreaBooksSupp.setText(controller.searchBookSellTitle(jTextFieldTitleSupp.getText()));
            jTextFieldTitleSupp.setText("");
            
        }
        
    }//GEN-LAST:event_jButtonSearchBookActionPerformed

    private void jTextFieldGenreSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenreSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenreSuppActionPerformed

    private void jRadioButtonSearchTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSearchTitleActionPerformed
        jTextFieldSNSupp.setEnabled(false);
        jTextFieldTitleSupp.setEnabled(true);
        jTextFieldAuthorSupp.setEnabled(false);
        jTextFieldPublisherSupp.setEnabled(false);
        jTextFieldGenreSupp.setEnabled(false);
        jTextFieldQuantitySupp.setEnabled(false);
        jTextFieldSNSupp.setText("");
        jTextFieldTitleSupp.setText("");
        jTextFieldAuthorSupp.setText("");
        jTextFieldPublisherSupp.setText("");
        jTextFieldGenreSupp.setText("");
        jTextFieldQuantitySupp.setText("");

        jButtonSearchBook.setEnabled(true);
        jButtonSaveDetail.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonSearchTitleActionPerformed

    private void jRadioButtonSearchSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSearchSNActionPerformed
        jTextFieldSNSupp.setEnabled(true);
        jTextFieldTitleSupp.setEnabled(false);
        jTextFieldAuthorSupp.setEnabled(false);
        jTextFieldPublisherSupp.setEnabled(false);
        jTextFieldGenreSupp.setEnabled(false);
        jTextFieldQuantitySupp.setEnabled(false);
        jTextFieldSNSupp.setText("");
        jTextFieldTitleSupp.setText("");
        jTextFieldAuthorSupp.setText("");
        jTextFieldPublisherSupp.setText("");
        jTextFieldGenreSupp.setText("");
        jTextFieldQuantitySupp.setText("");
        jButtonSearchBook.setEnabled(true);
        jButtonSaveDetail.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonSearchSNActionPerformed

    private void jRadioButtonSellBoookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSellBoookActionPerformed
        jTextFieldSNSupp.setEnabled(true);
        jTextFieldTitleSupp.setEnabled(true);
        jTextFieldAuthorSupp.setEnabled(true);
        jTextFieldPublisherSupp.setEnabled(true);
        jTextFieldGenreSupp.setEnabled(true);
        jTextFieldQuantitySupp.setEnabled(true);
        jTextFieldSNSupp.setText("");
        jTextFieldTitleSupp.setText("");
        jTextFieldAuthorSupp.setText("");
        jTextFieldPublisherSupp.setText("");
        jTextFieldGenreSupp.setText("");
        jTextFieldQuantitySupp.setText("");
        jButtonSearchBook.setEnabled(false);
        jButtonSaveDetail.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonSellBoookActionPerformed

    private void jRadioButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEnglishActionPerformed
        jLabelMainSupplier.setText(english.getString("Supplier"));
        jLabelBooksSupplier.setText(english.getString("Books"));
        jRadioButtonEnglish.setText(english.getString("English"));
        jRadioButtonFrench.setText(english.getString("French"));
        jButtonSaveDetail.setText(english.getString("Save"));
        jButtonSearchBook.setText(english.getString("Search"));
        jLabelSNSupplier.setText(english.getString("SN"));
        jLabelTitleSupplier.setText(english.getString("Title"));
        jLabelAuthorSupplier.setText(english.getString("Author"));
        jLabelPublisherSupplier.setText(english.getString("Publisher"));
        jLabelGenreSupplier.setText(english.getString("Price"));
        jLabelQuantitySupplier.setText(english.getString("Quantity"));
        
        jRadioButtonSearchTitle.setText(english.getString("SearchTitle"));
        jRadioButtonSearchSN.setText(english.getString("SN"));
        jRadioButtonSellBoook.setText(english.getString("Sell"));
        jLabelListBooksSupp.setText(english.getString("ListBooks"));
    }//GEN-LAST:event_jRadioButtonEnglishActionPerformed

    private void jRadioButtonFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFrenchActionPerformed
                                                       
        jLabelMainSupplier.setText(french.getString("Supplier"));
        jLabelBooksSupplier.setText(french.getString("Books"));
        jRadioButtonEnglish.setText(french.getString("English"));
        jRadioButtonFrench.setText(french.getString("French"));
        jButtonSaveDetail.setText(french.getString("Save"));
        jButtonSearchBook.setText(french.getString("Search"));
        jLabelSNSupplier.setText(french.getString("SN"));
        jLabelTitleSupplier.setText(french.getString("Title"));
        jLabelAuthorSupplier.setText(french.getString("Author"));
        jLabelPublisherSupplier.setText(french.getString("Publisher"));
        jLabelGenreSupplier.setText(french.getString("Price"));
        jLabelQuantitySupplier.setText(french.getString("Quantity"));
        
        jRadioButtonSearchTitle.setText(french.getString("SearchTitle"));
        jRadioButtonSearchSN.setText(french.getString("SN"));
        jRadioButtonSellBoook.setText(french.getString("Sell"));
        jLabelListBooksSupp.setText(french.getString("ListBooks"));
    }//GEN-LAST:event_jRadioButtonFrenchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonSaveDetail;
    private javax.swing.JButton jButtonSearchBook;
    private javax.swing.JLabel jLabelAuthorSupplier;
    private javax.swing.JLabel jLabelBooksSupplier;
    private javax.swing.JLabel jLabelGenreSupplier;
    private javax.swing.JLabel jLabelListBooksSupp;
    private javax.swing.JLabel jLabelMainSupplier;
    private javax.swing.JLabel jLabelPublisherSupplier;
    private javax.swing.JLabel jLabelQuantitySupplier;
    private javax.swing.JLabel jLabelSNSupplier;
    private javax.swing.JLabel jLabelTitleSupplier;
    private javax.swing.JRadioButton jRadioButtonEnglish;
    private javax.swing.JRadioButton jRadioButtonFrench;
    private javax.swing.JRadioButton jRadioButtonSearchSN;
    private javax.swing.JRadioButton jRadioButtonSearchTitle;
    private javax.swing.JRadioButton jRadioButtonSellBoook;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaBooks;
    private javax.swing.JTextArea jTextAreaBooksSupp;
    private javax.swing.JTextField jTextFieldAuthorSupp;
    private javax.swing.JTextField jTextFieldGenreSupp;
    private javax.swing.JTextField jTextFieldPublisherSupp;
    private javax.swing.JTextField jTextFieldQuantitySupp;
    private javax.swing.JTextField jTextFieldSNSupp;
    private javax.swing.JTextField jTextFieldTitleSupp;
    // End of variables declaration//GEN-END:variables
}
