/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package FinalProject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class MainStudent extends java.awt.Frame {
    private ResourceBundle english;
    private ResourceBundle french;   
    Controller controller = Controller.getInstance();

    /**
     * Creates new form MainLibrarian
     */
    public MainStudent() {
        initComponents();
        english = ResourceBundle.getBundle("Language_English");
        french = ResourceBundle.getBundle("Language_French", Locale.FRANCE);
        
        jButtonSave.setEnabled(false);
        jButtonSearch.setEnabled(false);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldSN.setEnabled(false);
        jTextFieldStudentId.setText("456");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabelMainStudent = new javax.swing.JLabel();
        jRadioButtonSearchTitle = new javax.swing.JRadioButton();
        jRadioButtonBorrow = new javax.swing.JRadioButton();
        jRadioButtonReturn = new javax.swing.JRadioButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelPublisher = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldAuthor = new javax.swing.JTextField();
        jTextFieldPublisher = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabelStudentId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBooks = new javax.swing.JTextArea();
        jLabelListBooks = new javax.swing.JLabel();
        jRadioButtonSearchAuthor = new javax.swing.JRadioButton();
        jRadioButtonSearchPublisher = new javax.swing.JRadioButton();
        jRadioButtonIssuedBooks = new javax.swing.JRadioButton();
        jLabelSN = new javax.swing.JLabel();
        jTextFieldSN = new javax.swing.JTextField();
        jRadioButtonEnglish = new javax.swing.JRadioButton();
        jRadioButtonFrench = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jTextFieldStudentId = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabelMainStudent.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 24)); // NOI18N
        jLabelMainStudent.setText("Student");

        buttonGroup1.add(jRadioButtonSearchTitle);
        jRadioButtonSearchTitle.setText("Search by Title");
        jRadioButtonSearchTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSearchTitleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBorrow);
        jRadioButtonBorrow.setText("Borrow");
        jRadioButtonBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBorrowActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonReturn);
        jRadioButtonReturn.setText("Return");
        jRadioButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReturnActionPerformed(evt);
            }
        });

        jLabelTitle.setText("Title");

        jLabelAuthor.setText("Author");

        jLabelPublisher.setText("Publisher");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStudentId.setText("Student Id");

        jTextAreaBooks.setColumns(8);
        jTextAreaBooks.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBooks);

        jLabelListBooks.setText("List of Books");

        buttonGroup1.add(jRadioButtonSearchAuthor);
        jRadioButtonSearchAuthor.setText("Search by Author");
        jRadioButtonSearchAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSearchAuthorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSearchPublisher);
        jRadioButtonSearchPublisher.setText("Search by Publisher");
        jRadioButtonSearchPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSearchPublisherActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonIssuedBooks);
        jRadioButtonIssuedBooks.setText("Issued books");
        jRadioButtonIssuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIssuedBooksActionPerformed(evt);
            }
        });

        jLabelSN.setText("SN");

        buttonGroup2.add(jRadioButtonEnglish);
        jRadioButtonEnglish.setSelected(true);
        jRadioButtonEnglish.setText("English");
        jRadioButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEnglishActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonFrench);
        jRadioButtonFrench.setText("French");
        jRadioButtonFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFrenchActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSearchAuthor)
                                    .addComponent(jRadioButtonSearchPublisher)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelMainStudent)
                                        .addComponent(jRadioButtonSearchTitle)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonBorrow)
                                    .addComponent(jRadioButtonReturn)
                                    .addComponent(jRadioButtonIssuedBooks)))
                            .addComponent(jLabelListBooks)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldAuthor)
                                        .addComponent(jLabelAuthor)
                                        .addComponent(jTextFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(jLabelPublisher)
                                        .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(jLabelSN)
                                        .addComponent(jTextFieldSN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelStudentId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonFrench, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonEnglish, javax.swing.GroupLayout.Alignment.TRAILING)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMainStudent)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelStudentId)
                                .addComponent(jTextFieldStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPublisher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonIssuedBooks)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonBorrow)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonReturn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSearchTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonSearchAuthor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonSearchPublisher)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelListBooks)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonEnglish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFrench)))
                .addGap(16, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    private void jRadioButtonSearchTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSearchTitleActionPerformed

        jTextFieldTitle.setEnabled(true);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        
        jButtonSave.setEnabled(false);
        jButtonSearch.setEnabled(true);
        
    }//GEN-LAST:event_jRadioButtonSearchTitleActionPerformed

    private void jRadioButtonBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBorrowActionPerformed
    
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldSN.setEnabled(true);
          
        jButtonSave.setEnabled(true);
        jButtonSearch.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonBorrowActionPerformed

    private void jRadioButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReturnActionPerformed
          
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldSN.setEnabled(true);
          
        jButtonSave.setEnabled(true);
        jButtonSearch.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButtonReturnActionPerformed

    private void jRadioButtonSearchAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSearchAuthorActionPerformed
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(true);
        jTextFieldPublisher.setEnabled(false);
        
        jButtonSave.setEnabled(false);
        jButtonSearch.setEnabled(true);
        
    }//GEN-LAST:event_jRadioButtonSearchAuthorActionPerformed

    private void jRadioButtonSearchPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSearchPublisherActionPerformed
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(true);
        
        jButtonSave.setEnabled(false);
        jButtonSearch.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonSearchPublisherActionPerformed

    private void jRadioButtonIssuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIssuedBooksActionPerformed
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldSN.setEnabled(false);
        
        jButtonSave.setEnabled(false);
        jButtonSearch.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonIssuedBooksActionPerformed

    private void jRadioButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEnglishActionPerformed
        jLabelMainStudent.setText(english.getString("Student"));
        jLabelStudentId.setText(english.getString("StudentI"));
        jRadioButtonEnglish.setText(english.getString("English"));
        jRadioButtonFrench.setText(english.getString("French"));
        jButtonSave.setText(english.getString("Save"));
        jButtonSearch.setText(english.getString("Search"));
        jLabelListBooks.setText(english.getString("ListBooks"));
        jRadioButtonSearchTitle.setText(english.getString("SearchTitle"));
        jRadioButtonSearchAuthor.setText(english.getString("SearchAuthor"));
        jRadioButtonSearchPublisher.setText(english.getString("SearchPublisher"));
        jRadioButtonReturn.setText(english.getString("Return"));
//        jRadioButtonBookCatalog.setText(english.getString("BookCatalog"));
        jRadioButtonIssuedBooks.setText(english.getString("IssuedBooks"));
        jRadioButtonBorrow.setText(english.getString("Borrow"));
        jLabelSN.setText(english.getString("SN"));
        jLabelTitle.setText(english.getString("Title"));
        jLabelAuthor.setText(english.getString("Author"));
        jLabelPublisher.setText(english.getString("Publisher"));
        jLabelStudentId.setText(english.getString("StudentId"));
    }//GEN-LAST:event_jRadioButtonEnglishActionPerformed

    private void jRadioButtonFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFrenchActionPerformed
        jLabelMainStudent.setText(french.getString("Student"));
        jLabelStudentId.setText(french.getString("StudentI"));
        jRadioButtonEnglish.setText(french.getString("English"));
        jRadioButtonFrench.setText(french.getString("French"));
        jButtonSave.setText(french.getString("Save"));
        jButtonSearch.setText(french.getString("Search"));
        jLabelListBooks.setText(french.getString("ListBooks"));
        jRadioButtonSearchTitle.setText(french.getString("SearchTitle"));
        jRadioButtonSearchAuthor.setText(french.getString("SearchAuthor"));
        jRadioButtonSearchPublisher.setText(french.getString("SearchPublisher"));
        jRadioButtonReturn.setText(french.getString("Return"));
//        jRadioButtonBookCatalog.setText(french.getString("BookCatalog"));
        jRadioButtonIssuedBooks.setText(french.getString("IssuedBooks"));
        jRadioButtonBorrow.setText(french.getString("Borrow"));
        jLabelSN.setText(french.getString("SN"));
        jLabelTitle.setText(french.getString("Title"));
        jLabelAuthor.setText(french.getString("Author"));
        jLabelPublisher.setText(french.getString("Publisher"));
        jLabelStudentId.setText(french.getString("StudentId"));
    }//GEN-LAST:event_jRadioButtonFrenchActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
       
//        Controller.getInstance();
        if(jRadioButtonSearchTitle.isSelected()){
            jTextAreaBooks.setText("");
            jTextAreaBooks.setText(controller.searchBookTitle(jTextFieldTitle.getText()));
            jTextFieldTitle.setText("");
        }
        
        else if(jRadioButtonSearchAuthor.isSelected()){
            jTextAreaBooks.setText("");
            jTextAreaBooks.setText(controller.searchBookAuthor(jTextFieldAuthor.getText()));
            jTextFieldAuthor.setText("");
        }
        
        else if(jRadioButtonSearchPublisher.isSelected()){
            jTextAreaBooks.setText("");
            jTextAreaBooks.setText(controller.searchBookPublisher(jTextFieldPublisher.getText()));
            jTextFieldPublisher.setText("");
        }
        else if(jRadioButtonIssuedBooks.isSelected()){
            
            int StId = Integer.parseInt(jTextFieldStudentId.getText());
            jTextAreaBooks.setText("");
            jTextAreaBooks.setText(controller.searchIssuedBooksID(StId));
        }
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
//        Controller.getInstance();
        
        if(jRadioButtonBorrow.isSelected())
        {
            int SN =Integer.parseInt(jTextFieldSN.getText());
            int StId = Integer.parseInt(jTextFieldStudentId.getText());
            String Status = "Borrowed";
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date = new Date();
            String frmtDate = dateFormat.format(date);
            jTextAreaBooks.setText(controller.saveIssueBook(SN,StId,Status,frmtDate));
            jTextFieldSN.setText("");
        }
        else if(jRadioButtonReturn.isSelected())
        {
            int Id =Integer.parseInt(jTextFieldSN.getText());
            jTextAreaBooks.setText(controller.returnIssueBook(Id));
            jTextFieldSN.setText("");
        }
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainStudent().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelListBooks;
    private javax.swing.JLabel jLabelMainStudent;
    private javax.swing.JLabel jLabelPublisher;
    private javax.swing.JLabel jLabelSN;
    private javax.swing.JLabel jLabelStudentId;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JRadioButton jRadioButtonBorrow;
    private javax.swing.JRadioButton jRadioButtonEnglish;
    private javax.swing.JRadioButton jRadioButtonFrench;
    private javax.swing.JRadioButton jRadioButtonIssuedBooks;
    private javax.swing.JRadioButton jRadioButtonReturn;
    private javax.swing.JRadioButton jRadioButtonSearchAuthor;
    private javax.swing.JRadioButton jRadioButtonSearchPublisher;
    private javax.swing.JRadioButton jRadioButtonSearchTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaBooks;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldPublisher;
    private javax.swing.JTextField jTextFieldSN;
    private javax.swing.JTextField jTextFieldStudentId;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables
}
