/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package FinalProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rober
 */
public class MainLibrarian extends java.awt.Frame {

    private ResourceBundle english;
    private ResourceBundle french;
    Controller controller = Controller.getInstance();
    /**
     * Creates new form MainLibrarian
     */
    
    Connection con;
    PreparedStatement pst;
    
    
    
    public MainLibrarian() {
        initComponents();
        english = ResourceBundle.getBundle("Language_English");
        french = ResourceBundle.getBundle("Language_French", Locale.FRANCE);

        jButtonSave.setEnabled(false);
        jButtonSearch.setEnabled(false);
        jTextFieldSN.setEnabled(false);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(false);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelMainLibrarian = new javax.swing.JLabel();
        jLabelBooks = new javax.swing.JLabel();
        jRadioButtonAdd = new javax.swing.JRadioButton();
        jRadioButtonIssue = new javax.swing.JRadioButton();
        jRadioButtonReturn = new javax.swing.JRadioButton();
        jRadioButtonBookCatalog = new javax.swing.JRadioButton();
        jRadioButtonIssuedBooks = new javax.swing.JRadioButton();
        jLabelSN = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelPublisher = new javax.swing.JLabel();
        jLabelGenre = new javax.swing.JLabel();
        jTextFieldSN = new javax.swing.JTextField();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldAuthor = new javax.swing.JTextField();
        jTextFieldPublisher = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jLabelStudent = new javax.swing.JLabel();
        jLabelStudentId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jTextFieldStudentId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldContact = new javax.swing.JTextField();
        jRadioButtonSearchStudent = new javax.swing.JRadioButton();
        jRadioButtonEnglish = new javax.swing.JRadioButton();
        jRadioButtonFrench = new javax.swing.JRadioButton();
        jRadioButtonCreateStudent = new javax.swing.JRadioButton();
        jLabelListBooks = new javax.swing.JLabel();
        jLabelListStudents = new javax.swing.JLabel();
        jLabelListIssuedBook = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaStudent = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaBooks = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaIssuedBooks = new javax.swing.JTextArea();
        jRadioButtonBookSN = new javax.swing.JRadioButton();

        jLabel6.setText("jLabel6");

        setPreferredSize(new java.awt.Dimension(900, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabelMainLibrarian.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 24)); // NOI18N
        jLabelMainLibrarian.setText("Librarian");

        jLabelBooks.setText("Books");

        buttonGroup1.add(jRadioButtonAdd);
        jRadioButtonAdd.setText("Add New Book");
        jRadioButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonIssue);
        jRadioButtonIssue.setText("Issue Book");
        jRadioButtonIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIssueActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonReturn);
        jRadioButtonReturn.setText("Return Book");
        jRadioButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReturnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBookCatalog);
        jRadioButtonBookCatalog.setText("Search by Book Title");
        jRadioButtonBookCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBookCatalogActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonIssuedBooks);
        jRadioButtonIssuedBooks.setText("Search Issued Books");
        jRadioButtonIssuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIssuedBooksActionPerformed(evt);
            }
        });

        jLabelSN.setText("SN");

        jLabelTitle.setText("Title");

        jLabelAuthor.setText("Author");

        jLabelPublisher.setText("Publisher");

        jLabelGenre.setText("Genre");

        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStudent.setText("Student");

        jLabelStudentId.setText("Student Id");

        jLabelName.setText("Name");

        jLabelContact.setText("Contact");

        buttonGroup1.add(jRadioButtonSearchStudent);
        jRadioButtonSearchStudent.setText("Search by StudentID");
        jRadioButtonSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSearchStudentActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonEnglish);
        jRadioButtonEnglish.setSelected(true);
        jRadioButtonEnglish.setText("English");
        jRadioButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEnglishActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonFrench);
        jRadioButtonFrench.setText("French");
        jRadioButtonFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFrenchActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCreateStudent);
        jRadioButtonCreateStudent.setText("Add New Student");
        jRadioButtonCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCreateStudentActionPerformed(evt);
            }
        });

        jLabelListBooks.setText("List of Books");

        jLabelListStudents.setText("List of Students");

        jLabelListIssuedBook.setText("List of Issued Books");

        jTextAreaStudent.setColumns(20);
        jTextAreaStudent.setRows(5);
        jScrollPane2.setViewportView(jTextAreaStudent);

        jTextAreaBooks.setColumns(20);
        jTextAreaBooks.setRows(5);
        jScrollPane4.setViewportView(jTextAreaBooks);

        jTextAreaIssuedBooks.setColumns(20);
        jTextAreaIssuedBooks.setRows(5);
        jScrollPane3.setViewportView(jTextAreaIssuedBooks);

        buttonGroup1.add(jRadioButtonBookSN);
        jRadioButtonBookSN.setText("Search by Book SN");
        jRadioButtonBookSN.setToolTipText("");
        jRadioButtonBookSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBookSNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabelListIssuedBook, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelListBooks)
                                    .addComponent(jButtonSave)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(570, 570, 570)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelListStudents)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(396, 396, 396))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabelMainLibrarian))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonIssue)
                                        .addComponent(jRadioButtonCreateStudent)
                                        .addComponent(jRadioButtonAdd)
                                        .addComponent(jRadioButtonReturn))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(jButtonSearch))
                                        .addComponent(jRadioButtonIssuedBooks)
                                        .addComponent(jRadioButtonBookSN)
                                        .addComponent(jRadioButtonBookCatalog)
                                        .addComponent(jRadioButtonSearchStudent))))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelBooks)
                                .addComponent(jLabelPublisher)
                                .addComponent(jLabelSN)
                                .addComponent(jTextFieldTitle)
                                .addComponent(jLabelAuthor)
                                .addComponent(jTextFieldAuthor)
                                .addComponent(jLabelTitle)
                                .addComponent(jTextFieldPublisher)
                                .addComponent(jTextFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelGenre)
                                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelStudentId)
                                .addComponent(jTextFieldStudentId)
                                .addComponent(jTextFieldName)
                                .addComponent(jLabelContact)
                                .addComponent(jLabelName)
                                .addComponent(jLabelStudent)
                                .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonFrench)
                                .addComponent(jRadioButtonEnglish)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelStudentId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelContact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBooks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelGenre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPublisher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jLabelListIssuedBook))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButtonEnglish)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButtonFrench)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelListStudents)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelMainLibrarian)
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonCreateStudent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonAdd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonIssue)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonReturn)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonSearchStudent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonBookCatalog)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonBookSN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonIssuedBooks)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(36, 36, 36)
                            .addComponent(jLabelListBooks)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jRadioButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddActionPerformed
        jTextFieldSN.setEnabled(true);
        jTextFieldTitle.setEnabled(true);
        jTextFieldAuthor.setEnabled(true);
        jTextFieldPublisher.setEnabled(true);
        jTextFieldPrice.setEnabled(true);

        jTextFieldStudentId.setEnabled(false);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSave.setEnabled(true);
        jButtonSearch.setEnabled(false);

    }//GEN-LAST:event_jRadioButtonAddActionPerformed

    private void jRadioButtonIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIssueActionPerformed
        jTextFieldSN.setEnabled(true);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(true);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSave.setEnabled(true);
        jButtonSearch.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonIssueActionPerformed

    private void jRadioButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReturnActionPerformed
        jTextFieldSN.setEnabled(true);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(true);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSave.setEnabled(true);
        jButtonSearch.setEnabled(false);

    }//GEN-LAST:event_jRadioButtonReturnActionPerformed

    private void jRadioButtonBookCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBookCatalogActionPerformed
        jTextFieldSN.setEnabled(false);
        jTextFieldTitle.setEnabled(true);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(false);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSearch.setEnabled(true);
        jButtonSave.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonBookCatalogActionPerformed

    private void jRadioButtonIssuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIssuedBooksActionPerformed
        jTextFieldSN.setEnabled(false);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(false);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSearch.setEnabled(true);
        jButtonSave.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonIssuedBooksActionPerformed

    private void jRadioButtonSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSearchStudentActionPerformed
        jTextFieldSN.setEnabled(false);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(true);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSearch.setEnabled(true);
        jButtonSave.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonSearchStudentActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
                  
//        Controller.getInstance();
        if(jRadioButtonCreateStudent.isSelected()){
            int StId = Integer.parseInt(jTextFieldStudentId.getText());
            String Name = jTextFieldName.getText();
            String Contact = jTextFieldContact.getText();
            jTextAreaStudent.setText(controller.addNewStudent(StId,Name,Contact));
            jTextFieldStudentId.setText("");
            jTextFieldName.setText("");
            jTextFieldContact.setText("");
            jTextFieldStudentId.setText("");
            jTextFieldName.setText("");
            jTextFieldContact.setText("");
        }
        
        else if(jRadioButtonAdd.isSelected())
        {
            int SN =Integer.parseInt(jTextFieldSN.getText());
            String title=(jTextFieldTitle.getText());
            String author = jTextFieldAuthor.getText();
            String  pub=jTextFieldPublisher.getText();
            String genre= jTextFieldPrice.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date = new Date();
            String fDate = dateFormat.format(date);
            jTextAreaBooks.setText(controller.saveNewBook(SN, title, author, pub, genre, fDate));
            jTextFieldSN.setText("");
            jTextFieldTitle.setText("");
            jTextFieldAuthor.setText("");
            jTextFieldPublisher.setText("");
            jTextFieldPrice.setText("");
        } 
        else if(jRadioButtonIssue.isSelected())
        {
            int SN =Integer.parseInt(jTextFieldSN.getText());
            int StId = Integer.parseInt(jTextFieldStudentId.getText());
            String Status = "Borrowed";
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date = new Date();
            String frmtDate = dateFormat.format(date);
            jTextAreaIssuedBooks.setText(controller.saveIssueBook(SN,StId,Status,frmtDate));
            jTextFieldSN.setText("");
            jTextFieldStudentId.setText("");
        }
        else if(jRadioButtonReturn.isSelected())
        {
            int Id =Integer.parseInt(jTextFieldSN.getText());
            jTextAreaIssuedBooks.setText(controller.returnIssueBook(Id));
            jTextFieldSN.setText("");
        }
        
        
        
        
        //Controller.getInstance().updatejTextAreaBooks(courseController);
    
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jRadioButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEnglishActionPerformed
        jLabelMainLibrarian.setText(english.getString("Librarian"));
        jLabelBooks.setText(english.getString("Books"));
        jLabelStudent.setText(english.getString("Student"));
        jRadioButtonEnglish.setText(english.getString("English"));
        jRadioButtonFrench.setText(english.getString("French"));
        jButtonSave.setText(english.getString("Save"));
        jButtonSearch.setText(english.getString("Search"));
        jLabelListBooks.setText(english.getString("ListBooks"));
        jLabelListStudents.setText(english.getString("ListStudent"));
        jRadioButtonAdd.setText(english.getString("Add"));
        jRadioButtonIssue.setText(english.getString("Issue"));
        jRadioButtonReturn.setText(english.getString("Return"));
        jRadioButtonBookCatalog.setText(english.getString("BookCatalog"));
        jRadioButtonIssuedBooks.setText(english.getString("IssuedBooks"));
        jRadioButtonSearchStudent.setText(english.getString("SearchStudent"));
        jLabelSN.setText(english.getString("SN"));
        jLabelTitle.setText(english.getString("Title"));
        jLabelAuthor.setText(english.getString("Author"));
        jLabelPublisher.setText(english.getString("Publisher"));
        jLabelGenre.setText(english.getString("Price"));
        jLabelStudentId.setText(english.getString("StudentId"));
        jLabelName.setText(english.getString("Name"));
        jLabelContact.setText(english.getString("Contact"));
    }//GEN-LAST:event_jRadioButtonEnglishActionPerformed

    private void jRadioButtonFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFrenchActionPerformed
        jLabelMainLibrarian.setText(french.getString("Librarian"));
        jLabelBooks.setText(french.getString("Books"));
        jLabelStudent.setText(french.getString("Student"));
        jRadioButtonEnglish.setText(french.getString("English"));
        jRadioButtonFrench.setText(french.getString("French"));
        jButtonSave.setText(french.getString("Save"));
        jButtonSearch.setText(french.getString("Search"));
        jLabelListBooks.setText(french.getString("ListBooks"));
        jLabelListStudents.setText(french.getString("ListStudent"));
        jRadioButtonAdd.setText(french.getString("Add"));
        jRadioButtonIssue.setText(french.getString("Issue"));
        jRadioButtonReturn.setText(french.getString("Return"));
        jRadioButtonBookCatalog.setText(french.getString("BookCatalog"));
        jRadioButtonIssuedBooks.setText(french.getString("IssuedBooks"));
        jRadioButtonSearchStudent.setText(french.getString("SearchStudent"));
        jLabelSN.setText(french.getString("SN"));
        jLabelTitle.setText(french.getString("Title"));
        jLabelAuthor.setText(french.getString("Author"));
        jLabelPublisher.setText(french.getString("Publisher"));
        jLabelGenre.setText(french.getString("Price"));
        jLabelStudentId.setText(french.getString("StudentId"));
        jLabelName.setText(french.getString("Name"));
        jLabelContact.setText(french.getString("Contact"));
    }//GEN-LAST:event_jRadioButtonFrenchActionPerformed

    private void jRadioButtonCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCreateStudentActionPerformed
        jTextFieldSN.setEnabled(false);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(true);
        jTextFieldName.setEnabled(true);
        jTextFieldContact.setEnabled(true);

        jButtonSearch.setEnabled(false);
        jButtonSave.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonCreateStudentActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        
//        Controller.getInstance();
        if(jRadioButtonSearchStudent.isSelected()){
            jTextAreaStudent.setText("");
            jTextAreaStudent.setText(controller.searchStudent(Integer.parseInt(jTextFieldStudentId.getText())));
            jTextFieldStudentId.setText("");
        }
        
        else if(jRadioButtonBookCatalog.isSelected()){
            jTextAreaBooks.setText("");
            jTextAreaBooks.setText(controller.searchBookTitle(jTextFieldTitle.getText()));
            jTextFieldTitle.setText("");
            
        }
        else if(jRadioButtonBookSN.isSelected()){
            jTextAreaBooks.setText("");
            jTextAreaBooks.setText(controller.searchBookSN(Integer.parseInt(jTextFieldSN.getText())));
            jTextFieldSN.setText("");
        }
        else if(jRadioButtonIssuedBooks.isSelected()){
            jTextAreaIssuedBooks.setText(controller.searchIssuedBooks());
        }
        
        
        
        
            
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jRadioButtonBookSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBookSNActionPerformed
        jTextFieldSN.setEnabled(true);
        jTextFieldTitle.setEnabled(false);
        jTextFieldAuthor.setEnabled(false);
        jTextFieldPublisher.setEnabled(false);
        jTextFieldPrice.setEnabled(false);

        jTextFieldStudentId.setEnabled(false);
        jTextFieldName.setEnabled(false);
        jTextFieldContact.setEnabled(false);

        jButtonSearch.setEnabled(true);
        jButtonSave.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonBookSNActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLibrarian().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelBooks;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelListBooks;
    private javax.swing.JLabel jLabelListIssuedBook;
    private javax.swing.JLabel jLabelListStudents;
    private javax.swing.JLabel jLabelMainLibrarian;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPublisher;
    private javax.swing.JLabel jLabelSN;
    private javax.swing.JLabel jLabelStudent;
    private javax.swing.JLabel jLabelStudentId;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JRadioButton jRadioButtonAdd;
    private javax.swing.JRadioButton jRadioButtonBookCatalog;
    private javax.swing.JRadioButton jRadioButtonBookSN;
    private javax.swing.JRadioButton jRadioButtonCreateStudent;
    private javax.swing.JRadioButton jRadioButtonEnglish;
    private javax.swing.JRadioButton jRadioButtonFrench;
    private javax.swing.JRadioButton jRadioButtonIssue;
    private javax.swing.JRadioButton jRadioButtonIssuedBooks;
    private javax.swing.JRadioButton jRadioButtonReturn;
    private javax.swing.JRadioButton jRadioButtonSearchStudent;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaBooks;
    private javax.swing.JTextArea jTextAreaIssuedBooks;
    private javax.swing.JTextArea jTextAreaStudent;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldPublisher;
    private javax.swing.JTextField jTextFieldSN;
    private javax.swing.JTextField jTextFieldStudentId;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables

    private void setStudentRegistered() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setStudentsRegistered(String StId, String Name, String Contact) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
